.TH PAPER-FORMATTING MACROS
.\"              List incomplete
.(c           \" Begin centred block
.(d           \" Begin delayed text
.(f           \" Begin footnote
.(l           \" Begin list
.(q           \" Begin major quote
.(x X         \" Begin indexed item in index
.(z           \" Begin floating keep
.)c           \" End centred block
.)d           \" End delayed text
.)f           \" End footnote
.)l           \" End list
.)q           \" End major quote
.)x           \" End index item
.)z           \" End floating keep
.++ M H       \" Define paper section
.+c T         \" Begin chapter
.1c           \" One column format on a new page
.2c           \" Two column format
.EN           \" Space after equation produced by eqn or neqn.
.EQ X Y       \" Precede equation; break out and add space
.GE           \" End gremlin picture
.GS           \" Begin gremlin picture
.PE           \" End pic picture
.PS           \" Begin pic picture
.TE           \" End table
.TH           \" End heading section of table [SKIPPED]
.TS X         \" Begin table; if X is "H" table has repeated heading
.b X          \" Print X in boldface; if no argument switch to boldface.
.ba +N        \" Augments the base indent by N. This indent is used to set the indent on regular text (like paragraphs).
.bc           \" Begin new column
.bi X         \" Print X in bold italics (nofill only)
.bu           \" Begin bulleted paragraph
.bx X         \" Print X in a box (nofill only)
.ef `X`Y`Z`   \" Set even footer to X Y Z
.eh `X`Y`Z`   \" Set even header to X Y Z
.fo `X`Y`Z`   \" Set footer to X Y Z
.hx           \" Suppress headers and footers on next page
.he `X`Y`Z`   \" Set header to X Y Z
.hl           \" Draw a horizontal line
.i X          \" Italicize X; if x missing, italic text follows.
.ip X Y       \" Start indented paragraph, with hanging tag X. Indentation is Y ens (default 5).
.lp           \" Start left-blocked paragraph
.np           \" Start numbered paragraph
.of `X`Y`Z`   \" Set odd footer to X Y Z
.oh `X`Y`Z`   \" Set odd header to X Y Z
.pd           \" Print delayed text
.pp           \" Begin paragraph. First line indented.
.r            \" Roman text follows
.re           \" Reset tabs to default values
.sh N X       \" Section head follows, font automatically bold. N is level of section, X is title of section.
.sk           \" Leave the next page blank. Only one page is remembered ahead.
.sm X         \" Set X in a smaller pointsize
.sz +N        \" Augment the point size by N points
.tp           \" Begin title page
.u X          \" Underline argument (even in troff) (Nofill only)
.uh           \" Like .sh but unnumbered
.xp X         \" Print index
