.TH MANUSCRIPTS

.SH COVER PAGE MACROS
.RP       \" Specify report format
.P1       \" Print the header on page 1
.DA       \" Print date
.ND       \" Print date
.TL       \" Set title
.AU       \" Set author
.AI       \" Set author's institution
.AB       \" Begin abstract
.AE       \" End abstract

.SH PARAGRAPHS
.PP       \" Begin paragraph with leading indent
.LP       \" Begin paragraph with no indent
.QP       \" Quoted paragraph
.XP       \" Exdented paragraph

.SH HEADINGS
.NH       \" Numbered heading
.SH       \" Unnumbered subheading

.SH HIGHLIGHTING
.CW       \" Constant width
.BX       \" Boxed text
.UL       \" Underlined text
.LG       \" Large text
.SM       \" Small text
.NL       \" Normal text

.SH LISTS
.IP       \" Item paragraph

.SH TAB STOPS
.TA       \" Reset tab stops to defaults

.SH DISPLAYS AND KEEPS
.DE       \" Display end
.De       \" Display end [DEPRECATED]
.DS       \" Display start
.Ds       \" Display start [DEPRECATED]
.KS       \" Keep start
.KE       \" Keep end
.KF       \" Floating keep
.B1       \" Begin box
.B2       \" End box

.SH PREPROCESSOR BLOCKS
.TS       \" Table start
.TE       \" Table end
.PS       \" Picture start
.PE       \" Picture end
.EQ       \" Equation start
.EN       \" Equation end
.[        \" Start reference
.]        \" End reference

.SH FOOTNOTES
.FS       \" Footnote start
.FE       \" Footnote end

.SH HEADERS AND FOOTERS
.OH 'left'centre'right'       \" Header: Odd-page
.EH 'left'centre'right'       \" Header: Even-page
.OF 'left'centre'right'       \" Footer: Odd-page
.EF 'left'centre'right'       \" Footer: Even-page
.PT                           \" Override header behaviour
.BT                           \" Override footer behaviour

.SH COLUMNS
.1C       \" Single-column mode
.2C       \" Two-column mode
.MC       \" Multicolumn mode

.SH TABLE OF CONTENTS
.XS       \" Table of contents: Begin
.XE       \" Table of contents: End
.TC       \" Print table of contents
.XA       \" Add TOC entry
.PX       \" Print table of contents without modifying page number
