.TH MEMORANDUM MACROS
.
.)E             \" Add heading text to the table of contents
.1C             \" Begin 1-column processing
.2C             \" Begin 2-column processing
.AE             \" Abstract end
.AF             \" Author's firm
.AL             \" Auto-increment list
.APP            \" Begin appendix
.APPSK          \" Same as .APP, but the page number is incremented with pages
.AS             \" Abstract start
.AST            \" Abstract title
.AT             \" Author's title
.AU             \" Author information
.AV             \" Approval signature
.AVL            \" Letter signature
.B1             \" Begin box
.B2             \" End box
.BE             \" End bottom block
.BL             \" Start bullet list
.BS             \" Bottom block start
.BVL            \" Begin variable-item list
.COVER          \" Begin coversheet definition
.COVEND         \" End coversheet definition
.DE             \" Display end
.DF             \" Begin floating display
.DL             \" Dash list start
.DS             \" Static display start
.EC             \" Equation title
.EF             \" Even-page footer
.EH             \" Even-page header
.EN             \" Equation end
.EOP            \" End-of-page user-defined macro
.EPIC           \" Draw a box with a given width and height
.EQ             \" Equation start
.EX [text]      \" Exhibit title
.FC             \" Formal closing (print "Yours very truly")
.FD             \" Footnote default format
.FE             \" Footnote end
.FG             \" Figure title
.FS             \" Footnote start
.GETHN          \" Get header number where `SETR [refname]` was placed
.GETPN          \" Get page number where `SETR [refname]` was placed
.GETR           \" Combine .GETHN and .GETPN
.GETST          \" Include string saved to .SETR
.H              \" Numbered section heading
.HC             \" Set hyphenation character
.HM             \" Heading mark style
.HU             \" Unnumbered section header
.HX             \" User-defined heading exit
.HY             \" User-defined heading exit
.HZ             \" User-defined heading exit
.IA             \" Begin specification of addressee and their address in letter style
.IE             \" End the address specification after .IA
.INITI          \" Initialise the new index system
.INITR          \" Initialise cross reference macros
.IND            \" Write a line in the index file
.INDP           \" Print the index
.ISODATE        \" Change the predefined date string in DT to ISO format
.LB             \" List-begin macro
.LC             \" List-status clear
.LE             \" List end
.LI             \" List item
.LT             \" Letter format
.LO             \" Letter options
.MC             \" Multiple columns
.ML             \" Marked list
.MT             \" Memorandum type
.MOVE           \" Move to a position
.MULB           \" Begin a special multi-column mode
.MULN           \" Begin the next column
.MULE           \" End the multi-column mode and print columns
.nP             \" Print numbered paragraph with header level two
.NCOL           \" Force printing to the next column
.NS             \" Print different types of notations
.ND             \" New date
.OF             \" Odd-page footer
.OH             \" Odd-page header
.OP             \" Odd-page text
.P              \" New paragraph
.PGFORM         \" Page formatting
.PGNH           \" No header on next page
.PIC            \" Include a PostScript file in the document
.PE             \" Picture end
.PF             \" Page footer
.PH             \" Page header
.PS             \" Picture start
.PX             \" Page header user-defined exit
.RD             \" Read from standard input to diversion and/or string
.RF             \" Reference end
.RL             \" Reference list start
.RP             \" Produce reference page
.RS             \" Begin an automatically numbered reference definition
.S              \" Set point-size and vertical spacing
.SA             \" Set right-margin justification
.SETR           \" Remember the current header and page number as [refname]
.SG             \" Signature line
.SK             \" Skip pages
.SM             \" Make a string smaller
.SP             \" Space vertically
.TAB            \" Reset tabs to every 5n
.TB             \" Table title
.TC             \" Table of contents
.TE             \" Table end
.TL             \" Begin title of memorandum
.TM             \" Technical memorandum numbers used in .MT
.TP             \" Top-of-page user-defined macro
.TS             \" Table start
.TX             \" User-defined table of contents exit
.TY             \" User-defined table of contents exit
.VERBON         \" Begin verbatim output in a monospace font
.VERBOFF        \" End verbatim output
.VL             \" Variable-item list
.VM             \" Vertical margin
.WA             \" Writer's address/name
.WE             \" End of .WA macro
.WC             \" Footnote and display width control
