.TH SYNTAX-TESTS 1
.SH NAME
syntax\-tests \- RTFM
.SH SYNOPSIS

.nf
.B Bold Bold Bold Bold Still Bold
.I Italic Italic Italic Still Italic
Normal Plain Roman Ordinary Etc
.B
Also bold
Not bold
.I 
Also italic
'	\" Blank lines:
ALPHA
'  	  		 	
'	  	 	
'  
'  
BRAVO
.\" More blank lines:
. 
. 	  	
sss

.\" Comment
.ul 1 \" something
qwd
.
.\" Font families
\fB BOLD  \fI Italic \fP Plain


\f1 ONE \f2 TWO \f3 THREE \f4 FOUR
.nf
1: Plain
2: Italic
3: Bold
4: Bold Italic
.fi
.
