.TH TITLE
.SH SECTION

\f3BOLD
BOLD
BOLD
BOLD
BOLD
\f2ALSO
ITALIC
LEL
\fBBUT
MOSTLY
BOLD
.M8 SOME UNRECOGNISED MACRO
.tp Not .TP, don't stop
YEAH
STILL
BOLD
.TP
Title 1

Plain
Plain
Plain
\f4BOLD
BOLD
BOLD
.ds name value
YEP
STILL
BOLD


.TP
Title
2

Body
\fB \- \- _BBBBBBB__ TITLE __BBBBBBBB
.ds name value
Description
