.TH REPEATING-FONTS 1

.\"============================= BOLD | ITALIC =================================
.SH .BI: BOLD + ITALIC
.nf

.BI Bold Italic "Bold Bold
Bold" "Italic Italic Italic" Bold

.BI Bold Italic "Bold\
Bold" "Italic Italic Italic" Bold

.BI Bold Italic\
Italic\
Italic\
Italic Bold Italic

.BI "Bold"Italic Bold

.BI "Bold""Bold" Italic

.BI "Bold" "Something really\
really long and italic" Bold Italic Bold

.BI "Bold" "Something really\
really"" long and really italic

Plain

.BI "Bold" "Italic
Should also be plain



.\"============================= BOLD | ROMAN ==================================
.SH .BR: BOLD + ROMAN
.nf

.BR Bold Roman "Bold Bold
Bold" "Roman Roman Roman" Bold

.BR Bold Roman "Bold\
Bold" "Roman Roman Roman" Bold

.BR Bold Roman\
Roman\
Roman\
Roman Bold Roman

.BR "Bold"Roman Bold

.BR "Bold""Bold" Roman

.BR "Bold" "Something really\
really long and regular" Bold Roman Bold

.BR "Bold" "Something really\
really"" long and really regular

Plain

.BR "Bold" "Roman
Should also be plain




.\"============================= ITALIC | BOLD =================================
.SH .IB: ITALIC + BOLD
.nf

.IB Italic Bold "Italic Italic
Italic" "Bold Bold Bold" Italic

.IB Italic Bold "Italic\
Italic" "Bold Bold Bold" Italic

.IB Italic Bold\
Bold\
Bold\
Bold Italic Bold

.IB "Italic"Bold Italic

.IB "Italic""Italic" Bold

.IB "Italic" "Something really\
really long and bold" Italic Bold Italic

.IB "Italic" "Something really\
really"" long and really bold

Plain

.IB "Italic" "Bold
Should also be plain



.\"============================= ITALIC | ROMAN ================================
.SH .IR: ITALIC + ROMAN
.nf

.IR Italic Roman "Italic Italic
Italic" "Roman Roman Roman" Italic

.IR Italic Roman "Italic\
Italic" "Roman Roman Roman" Italic

.IR Italic Roman\
Roman\
Roman\
Roman Italic Roman

.IR "Italic"Roman Italic

.IR "Italic""Italic" Roman

.IR "Italic" "Something really\
really long and regular" Italic Roman Italic

.IR "Italic" "Something really\
really"" long and really regular

Plain

.IR "Italic" "Roman
Should also be plain



.\"============================= ROMAN | BOLD ==================================
.SH .RB: ROMAN + BOLD
.nf

.RB Roman Bold "Roman Roman
Roman" "Bold Bold Bold" Roman

.RB Roman Bold "Roman\
Roman" "Bold Bold Bold" Roman

.RB Roman Bold\
Bold\
Bold\
Bold Roman Bold

.RB "Roman"Bold Roman

.RB "Roman""Roman" Bold

.RB "Roman" "Something really\
really long and bold" Roman Bold Roman

.RB "Roman" "Something really\
really"" long and really bold

Plain

.RB "Roman" "Bold
Should also be plain



.\"============================= ROMAN | ITALIC ================================
.SH .RI: ROMAN + ITALIC
.nf

.RI Roman Italic "Roman Roman
Roman" "Italic Italic Italic" Roman

.RI Roman Italic "Roman\
Roman" "Italic Italic Italic" Roman

.RI Roman Italic\
Italic\
Italic\
Italic Roman Italic

.RI "Roman"Italic Roman

.RI "Roman""Roman" Italic

.RI "Roman" "Something really\
really long and italic" Roman Italic Roman

.RI "Roman" "Something really\
really"" long and really italic

Plain

.RI "Roman" "Italic
Should also be plain
