.TH REPEATING-FONTS 1
.SH ALTERNATING FONT MACROS

.\" Single-line
.
.BI Bold "Italic" "Bold""aa"

.BI "ALTERNAT"ING" "FONT MACROS
.PP
Italic "Bold'BOLD'Bold" Italic
Bold" Italic Bold "Italic" Bold Italic
PLAIN

.BI "BOLD" "italic" BOLD"BOLD"BOLD italic



.\" Multiline
.BI Bold Italic Bold\
Italic

.BI Bold Italic Bold \
Italic


.\" Other combinations
.IB Italic Bold Italic Bold "Italic Italic Italic" Bold Italic
.IR Italic Normal Italic Roman Italic Roman
.BR Bold (Normal) Bold Normal Bold Normal
.RI Normal Italic Normal Italic Normal Italic
.RB Normal Bold Normal Bold Normal Bold
