.TH REPEATING-FONTS 1
.SH ALTERNATING FONT MACROS
.nf

.BI Bold Italic "Bold Bold
Bold" "Italic Italic Italic" Bold

.BI Bold Italic "Bold\
Bold" "Italic Italic Italic" Bold

.BI Bold Italic\
Italic\
Italic\
Italic Bold Italic

.BI "Bold\
Bold Bold Bold\
Bold\
Bold" "Italic Italic\
Italic Italic Italic\
Italic\
Italic" Bold Italic

.BI "Bold"Italic Bold

.BI "Bold""Bold" Italic

.BI "Bold" "Something really\
really long and italic" Bold Italic Bold

.BI "Bold" "Something really\
really"" long and really italic

Plain

.BI "Bold" "Italic
