.TH SYNTAX-TESTS 1
.SH NAME
syntax\-tests \- RTFM
.SH SYNOPSIS

.nf
.B Bold Bold Bold Bold Still Bold
.I Italic Italic Italic Still Italic
Normal Plain Roman Ordinary Etc
.B
Also bold
Not bold

.I 
Also italic

.SH MULTILINE FORMATTING

.BI "bold" we "we\
sfd" asafasf wfsf \
qewrs dwed a

asfagf

.SH SDGSGSG
.IB italic bold italic bold\a italic bold\

 GAWD bold we wed asafasf wfsf\
qewrs dwed a

.BI Bold Italic Bold Italic

.IB Italic Bold Italic Bold "Italic Italic Italic" Bold Italic
.IR Italic Normal Italic Roman Italic Roman
.BR Bold (Normal) Bold Normal Bold Normal
.RI Normal Italic Normal Italic Normal Italic
.RB Normal Bold Normal Bold Normal Bold

sss

.\" Comment
.ul 1 \" something
qwd
.
.\" Font families
\fB BOLD  \fI Italic \fP Plain


\f1 ONE \f2 TWO \f3 THREE \f4 FOUR
.nf
1: Plain
2: Italic
3: Bold
4: Bold Italic
.fi
.
