.TH "MY OWN MACROS" (MOM)


.SH TYPESETTING MACROS

.SS Paper size, margins, line length
.PAPER                      \" Set common paper sizes (letter, A4, etc)
.PAGEWIDTH                  \" Set a custom page width
.PAGELENGTH                 \" Set a custom page length
.PAGE                       \" Set explicit page dimensions and margins
.T_MARGIN                   \" Set a top margin
.B_MARGIN                   \" Set a bottom margin
.L_MARGIN                   \" Set a left margin (page offset)
.R_MARGIN                   \" Set a right margin
.LL                         \" Set a line length

.SS Family, font, point-size
.FAMILY                     \" Set the family of type
.FT                         \" Set the font style (roman, italic, etc)
.FALLBACK_FONT              \" Establish a fallback font (for missing fonts)
.PT_SIZE                    \" Set the point-size
\*[SIZE n]                  \" Change the point-size inline

.SS Font modifications
\" Pseudo-italic
.SETSLANT                   \" Set slant degree
\*[SLANT]                   \" Invoke pseudo-italic inline
\*[SLANTX]                  \" Disable pseudo-italic inline

\" Pseudo-bold
.SETBOLDER                  \" Set emboldening amount
\*[BOLDER]                  \" Invoke pseudo-bold inline
\*[BOLDERX]                 \" Disable pseudo-bold inline

\" Pseudo-condensed
.CONDENSE                   \" Set pseudo-condense amount
\*[COND]                    \" Invoke pseudo-condensing inline
\*[CONDX]                   \" Disable pseudo-condensing inline

\" Pseudo-extended
.EXTEND                     \" Set the amount to pseudo-extend
\*[EXT]                     \" Invoke pseudo-extending inline
\*[EXTX]                    \" Disable pseudo-condensing inline

.SS Leading (line-spacing)
.LS                         \" Set line-spacing (leading)
.AUTOLEAD                   \" Set line-spacing relative to point-size

.SS Justification, quad direction, line-by-line setting, breaking lines
.JUSTIFY                    \" Justify text to both margins
.QUAD                       \" "Justify" text left, centre, or right
.LEFT                       \" Set line-by-line quad left
.CENTER                     \" Set line-by-line quad centre
.RIGHT                      \" Set line-by-line quad right
.SPREAD                     \" Force-justify a line
.EL                         \" Break a line without advancing on the page

.SS Hyphenation
.HY                         \" Automatic hyphenation on/off
.HY_SET                     \" Set automatic hyphenation parameters

.SS Word and sentence spacing
.WS                         \" Set the minimum word space-size
.SS                         \" Set the sentence space-size

.SS Kerning, ligatures, smartquotes
.KERN                       \" Automatic character pair kerning on/off
\*[BU n]                    \" Move character pairs closer together inline
\*[FU n]                    \" Move character pairs further apart inline
.RW                         \" Uniformly tighten space between characters
.EW                         \" Uniformly loosen space between characters
.BR_AT_LINE_KERN            \" Break previous line when RW or EW is invoked
.LIGATURES                  \" Automatic generation of ligatures on/off
.SMARTQUOTES                \" Smartquoting on/off

.SS Horizontal and vertical movements, columnar setting
.ALD                        \" Move downards on the page
.RLD                        \" Move upwards on the page
.SPACE                      \" Insert space between lines on a page
\*[DOWN n]                  \" Temporarily move downwards in a line
\*[UP n]                    \" Temporarily move upwards in a line
\*[FWD n]                   \" Move forward in a line
\*[BCK n]                   \" Move backwards in a line
.MCO                        \" Multiple columns on
.MCR                        \" Recto vertical position of column start
.MCX                        \" Multiple columns off, advance past longest column

.SS Indents
.IL                         \" Set and turn on a left indent
.IQ                         \" Quit (exit) all indents
.TI                         \" Set and turn on a temporary (one line) indent
.HI                         \" Set and turn on a hanging indent
.ILX                        \" Left indents off
.IRX                        \" Right indents off
.IBX                        \" Both left and right indents off

.SS Tabs
.TAB_SET                    \" Set up a typesetting tab
.TAB <n>                    \" Call tab <n>
.TQ                         \" Quit (exit) tabs
\*[ST<n>]...                \" String tabs (mark tab positions inline)
\*[ST<n>X]
.TN                         \" Move to tab<n+1> without advancing on the page
.ST                         \" Set quad/fill for string tabs

.SS Underscoring, underlining
.UNDERSCORE                 \" Underscore
.UNDERSCORE2                \" Double underscore
.UNDERLINE                  \" Underline (fixed width fonts only)
\*[UL]...                   \" Invoke underlining inline (fixed width fonts only)
\*[ULX]

.SS Superscipts
\*[SUP]...\*[SUPX]          \" Superscript
\*[CONDSUP]...\*[CONDSUPX]  \" Pseudo-condensed superscript
\*[EXTSUP]...\*[EXTSUPX]    \" Pseudo extended supercript
SUPERSCRIPT_RAISE_AMOUNT    \" Vertical offset of superscripts

.SS Nested lists
.LIST                       \" Begin a list
.ITEM                       \" Begin an item in a list
.SHIFT_LIST                 \" Change the indent of a list
.RESET_LIST                 \" Clear and reset a list's enumerator
.PAD_LIST_DIGITS            \" Reserve space for digits

.SS Colour
.NEWCOLOR                   \" Initialize (define) a colour
.COLOR                      \" Begin using an initialised colour
.XCOLOR                     \" Initialize a "named" X colour
\*[<colorname>]             \" Begin using an initialised colour inline

.SS Dropcaps
.DROPCAP                    \" Set a dropcap
.DROPCAP_FAMILY             \" Set a dropcap's family
.DROPCAP_FONT               \" Set a dropcap's font style
.DROPCAP_COLOR              \" Set a dropcap's colour
.DROPCAP_ADJUST             \" Adjust size of a dropcap
.DROPCAP_GUTTER             \" Adjust space between a dropcap and regular text

.SS Utilities
.ALIAS                      \" Give a macro a new name
.CAPS                       \" Set type all caps
.COMMENT                    \" Silently embed comments in a document
.ESC_CHAR                   \" Change the default escape character
\*[LEADER]                  \" Insert leaders at the end of a line
.LEADER_CHARACTER           \" Change the character used for leaders
.NEWPAGE                    \" Break to a new page
.PAD                        \" Insert equalised whitespace into a line
.PAD_MARKER                 \" Change the pad marker
\*[RULE]                    \" Draw a full measure rule
.SIZESPECS                  \" Get cap-height, x-height and descender depth
.SILENT                     \" Output processing off or on
.TRAP                       \" Enable or disable page position traps

.SS Graphical objects and images
.DRH                        \" Draw a horizontal rule
.DRV                        \" Draw a vertical rule
.DBX                        \" Draw a box
.DCL                        \" Draw a circle (ellipse)
.RULE_WEIGHT                \" Set weight of rules drawn with \*[RULE]
.PDF_IMAGE                  \" Insert a PDF image
.PSPIC                      \" Insert a PostScript image


.SH DOCUMENT PROCESSING MACROS

.SS Reference macros
.TITLE                      \" Document title
.DOCTITLE                   \" Overall document title (if different from TITLE)
.ENDNOTE_TITLE              \" Document/chapter id string for endnotes
.CHAPTER                    \" Chapter number
.CHAPTER_TITLE              \" Chapter title
.CHAPTER_STRING             \" What to use in place of “Chapter”
.SUBTITLE                   \" Document subtitle
.AUTHOR                     \" Document author(s)
.DOC_COVERTITLE             \" Document title cover
.COVERTITLE                 \" Section cover title
.COPYRIGHT                  \" Copyright
.MISC                       \" Miscellaneous cover information
.DRAFT                      \" Document's draft number
.DRAFT_STRING               \" What to use in place of “Draft”
.REVISION                   \" Document's revision number
.REVISION_STRING            \" What to use in place of “Revision”

.SS General document formatting directives
.DOCTYPE                    \" General document type
.COPYSTYLE                  \" Draft or final copy
.PRINTSTYLE                 \" Typeset or “typewritten”


.SS Line numbering
.NUMBER_LINES               \" Automatic line numbering on/off
.NUMBER_QUOTE_LINES         \" Numbering of QUOTE lines on/off
.NUMBER_BLOCKQUOTE_LINES    \" Numbering of BLOCKQUOTE lines on/off

.SS Set documents in columns
.COLUMNS
.COL_NEXT
.COL_BREAK


.SS TYPEWRITE control macros
.UNDERLINE_ITALIC           \" Underlining of italics on
.UNDERLINE_QUOTES           \" Underlining of QUOTEs on/off
.ITALIC_MEANS_ITALIC        \" Use real italics (not underlining)
.UNDERLINE_SLANT            \" Underlining of pseudo-italics on
.SLANT_MEANS_SLANT          \" Use pseudo-italics (not underlining)


.SS Initiate document processing
.START                      \" Begin document processing

.SS Epigraphs
.EPIGRAPH                   \" Set an epigraph underneath the docheader
.EPIGRAPH_FAMILY
.EPIGRAPH_FONT
.EPIGRAPH_SIZE
.EPIGRAPH_COLOR
.EPIGRAPH_AUTOLEAD


.SS Headings
.HEADING                   \" Hierarchical headings
.HEADING_STYLE             \" Set style parameters for heading levels
.PREFIX_CHAPTER_NUMBER     \" Add chapter number to heading numbering

.SS Paragraphs
.PP                        \" Set a paragraph
.PP_FONT                   \" Globally change font of regular paragraphs
.PARA_INDENT               \" Set the paragraph first-line indent
.INDENT_FIRST_PARAS        \" Indenting of paragraph first-lines on/off
.PARA_SPACE                \" Linespace between paragraphs on/off


.SS Quotes (line for line verbatim quotes)
.QUOTE                     \" Set quoted text line for line
.QUOTE_FAMILY
.QUOTE_FONT
.QUOTE_SIZE
.QUOTE_AUTOLEAD
.QUOTE_COLOR
.QUOTE_INDENT
.ALWAYS_FULLSPACE_QUOTES   \" Control vertical space around quotes


.SS Blockquotes (cited passages of text)
.BLOCKQUOTE                \" Set longer passages of cited text
.BLOCKQUOTE_FAMILY
.BLOCKQUOTE_FONT
.BLOCKQUOTE_SIZE
.BLOCKQUOTE_AUTOLEAD
.BLOCKQUOTE_COLOR
.BLOCKQUOTE_QUAD
.BLOCKQUOTE_INDENT
.ALWAYS_FULLSPACE_BLOCKQUOTES  \" Control vertical spacing
.CITE
.CITATION


.SS Floats
.FLOAT                      \" Keep blocks of input together, output on next page if necessary

.SS Images and graphics
.PDF_IMAGE                  \" Inserting pdf images
.PDF_IMAGE_FRAME            \" Set parameters for pdf image frames
.PSPIC                      \" Inserting PostScript images

.SS eqn support
.EQ                         \" Begin an eqn block
.EN                         \" End an eqn block

.SS pic support
.PS                         \" Begin a pic block
.PE                         \" End a pic block
.PIC_TEXT_STYLE             \" Set style for pic text

.SS tbl support
.TS                         \" Begin a tbl block
.TH                         \" Running table header (after TS H)
.TE                         \" End tbl block

.SS Captions and labels
.AUTOLABEL                  \" Auto-label figures, tables, equations
.CAPTION_AFTER_LABEL        \" Place captions after labels
.MLA                        \" MLA-style labelling and captioning
.CAPTIONS                   \" Set style for captions
.LABELS                     \" Set style for labels
.SOURCES                    \" Set style for sources (tbl only)


.SS Lists of Figures, Tables, and Equations
.LIST_OF_FIGURES            \" Generate a List of Figures
.LIST_OF_TABLES             \" Generate a List of Tables
.LIST_OF_EQUATIONS          \" Generate a List of Equations
.LISTS_STYLE                \" Set style parameters for Lists

.SS Code snippets
.CODE                       \" Set a code snippet
.CODE_FAMILY
.CODE_FONT
.CODE_COLOR
.CODE_SIZE                  \" Code size as a percentage of prevailing text

.SS Author linebreaks (section breaks)
.LINEBREAK                  \" Insert an author linebreak (section break)
.LINEBREAK_CHAR             \" Character to use for author linebreaks
.LINEBREAK_COLOR            \" Colour of author linebreak character
.SECTION
.SECTION_CHAR
.SECTION_COLOR


.SS Document termination string
.FINIS                      \" Insert a document termination string
.FINIS_STRING               \" Set the document termination string
.FINIS_STRING_CAPS          \" Capitalization of termination string
.FINIS_COLOR                \" Set the document termination string colour

.SS Footnotes
.FOOTNOTE                   \" Set a footnote
.FOOTNOTE_MARKERS           \" Footnote markers on/off
.FOOTNOTE_MARKER_STYLE      \" Type of footnote marker to use
.RESET_FOOTNOTE_NUMBER      \" Reset footnote numbering
.FOOTNOTE_RULE              \" Footnote separator rule on/off
.FOOTNOTE_RULE_ADJ          \" Adjust position of footnote rule
.FOOTNOTE_RULE_LENGTH       \" Adjust length of footnote rule
.FOOTNOTES_RUN_ON           \" Instruct footnotes to be continuous


.SS Endnotes
.ENDNOTE                    \" Set an endnote
\*[EN-MARK]                 \" Mark initial line of a range of line numbers (for use with line numbered endnotes)
.ENDNOTES                   \" Output endnotes
.ENDNOTE_FAMILY
.ENDNOTE_FONT
.ENDNOTE_QUAD
.ENDNOTE_PT_SIZE
.ENDNOTE_LEAD
.ENDNOTE_SPACING
.SINGLESPACE_ENDNOTES
.ENDNOTE_PARA_INDENT
.ENDNOTE_PARA_SPACE
.ENDNOTES_NO_COLUMNS
.ENDNOTES_PAGENUM_STYLE
.ENDNOTES_FIRST_PAGENUMBER
.ENDNOTES_NO_FIRST_PAGENUM
.SUSPEND_PAGINATION
.RESTORE_PAGINATION
.HEADER_CENTER
.FOOTER_CENTER
.ENDNOTES_HEADER_CENTER
.ENDNOTES_ALLOWS_HEADERS
.ENDNOTE_STRING
.ENDNOTE_STRING_FAMILY
.ENDNOTE_STRING_FONT
.ENDNOTE_STRING_SIZE
.ENDNOTE_STRING_QUAD
.ENDNOTE_STRING_COLOR
.ENDNOTE_STRING_ADVANCE
.ENDNOTE_STRING_UNDERSCORE
.ENDNOTE_STRING_UNDERLINE
.ENDNOTE_STRING_CAPS
.ENDNOTE_TITLE
.ENDNOTE_TITLE_FAMILY
.ENDNOTE_TITLE_FONT
.ENDNOTE_TITLE_SIZE
.ENDNOTE_TITLE_QUAD
.ENDNOTE_TITLE_UNDERSCORE
.ENDNOTE_TITLE_UNDERLINE
.ENDNOTE_MARKER_STYLE
.ENDNOTE_NUMBERS_ALIGN
.ENDNOTE_LINENUMBER_GAP
.ENDNOTE_LINENUMBER_BRACKETS
.ENDNOTE_LINENUMBER_SEPARATOR
.ENDNOTE_NUMBER_FAMILY
.ENDNOTE_NUMBER_FONT
.ENDNOTE_NUMBER_SIZE
.ENDNOTE_LINENUMBER_FAMILY
.ENDNOTE_LINENUMBER_FONT
.ENDNOTE_LINENUMBER_SIZE


.SS Margin notes
.MN_INIT            \" Initialize margin notes
.MN                 \" Set a margin note

.SS Bibliographic references
.REF                \" Begin a reference
.FOOTNOTE_REFS      \" Place references in footnotes
.ENDNOTE_REFS       \" Place references in endnotes
.REF( / REF)        \" Put parentheses around embedded references
.REF[ / REF]        \" Put square brackets around embedded references
.REF{ / REF}        \" Put curly braces around mbedded references
.BIBLIOGRAPHY       \" Output a bibliography
.BIBLIOGRAPHY_TYPE
.BIBLIOGRAPHY_PT_SIZE
.BIBLIOGRAPHY_LEAD
.BIBLIOGRAPHY_SPACING
.SINGLESPACE_BIBLIOGRAPHY
.BIBLIOGRAPHY_NO_COLUMNS
.BIBLIOGRAPHY_PAGENUM_STYLE
.BIBILOGRAPHY_FIRST_PAGENUMBER
.BIBLIOGRAPHY_NO_FIRST_PAGENUM
.SUSPEND_PAGINATION
.RESTORE_PAGINATION
.BIBLIOGRAPHY_ALLOWS_HEADERS
.BIBLIOGRAPHY_STRING
.BIBLIOGRAPHY_STRING_FAMILY
.BIBLIOGRAPHY_STRING_FONT
.BIBLIOGRAPHY_STRING_SIZE
.BIBLIOGRAPHY_STRING_QUAD
.BIBLIOGRAPHY_STRING_ADVANCE
.BIBLIOGRAPHY_STRING_UNDERSCORE
.BIBLIOGRAPHY_STRING_UNDERLINE
.BIBLIOGRAPHY_STRING_CAPS


.SS Tables of Contents
.TOC        \" Output a table of contents
.TOC_FAMILY
.TOC_PT_SIZE
.TOC_LEAD
.PAGINATE_TOC
.TOC_PAGENUM_STYLE
.TOC_HEADER_STRING
.TOC_HEADER_FAMILY
.TOC_HEADER_FONT
.TOC_HEADER_SIZE
.TOC_HEADER_QUAD
.TOC_PN_FAMILY
.TOC_PN_FONT
.TOC_PN_SIZE
.TOC_TITLE_STYLE
.TOC_TITLE_ENTRY
.TOC_ENTRY_STYLE
.TOC_ENTRY_NUMBER
.TOC_ENTRY_NUMBERS
.TOC_APPENDS_AUTHOR
.TOC_TITLE_ENTRY
.SPACE_TOC_ITEMS
.TOC_PADDING
.TOC_RV_SWITCH


.SS Letter (correspondence) macros
.DATE               \" Letter's date
.FROM               \" Letter's addresser
.TO                 \" Letter's addressee
.GREETING           \" Letter's salutation
.CLOSING            \" Letter's closing salutation
.CLOSING_INDENT     \" Indentation of the closing salutation
.SIGNATURE_SPACE    \" Room to leave for the signature
.NO_SUITE           \" Printing of "next page number" off or on


.SS Changing global print style parameters after START
.DOC_LEFT_MARGIN    \" Left margin of everything on the page
.DOC_RIGHT_MARGIN   \" Right margin of everything on the page
.DOC_LINE_LENGTH    \" Document's base line length
.DOC_FAMILY         \" Document's base family
.DOC_PT_SIZE        \" Document's base point size
.DOC_LEAD           \" Document's base lead
.DOC_QUAD           \" Document's base quad directions

.SS Managing a document's first-page header
.DOCHEADER          \" Document first-page header on/off
.ATTRIBUTE_COLOR
.ATTRIBUTE_STRING
.AUTHOR_COLOR
.AUTHOR_FAMILY
.AUTHOR_FONT
.AUTHOR_SIZE
.CHAPTER_TITLE_COLOR
.CHAPTER_TITLE_FAMILY
.CHAPTER_TITLE_FONT
.CHAPTER_TITLE_SIZE
.DOCHEADER_ADVANCE
.DOCHEADER_COLOR
.DOCHEADER_FAMILY
.DOCHEADER_LEAD
.DOCHEADER_QUAD
.DOCTYPE_COLOR
.DOCTYPE_FAMILY
.DOCTYPE_FONT
.DOCTYPE_SIZE
.SUBTITLE_COLOR
.SUBTITLE_FAMILY
.SUBTITLE_FONT
.SUBTITLE_SIZE
.TITLE_COLOR
.TITLE_FAMILY
.TITLE_FONT
.TITLE_SIZE


.SS Managing page headers and footers
.HEADERS              \" Page headers on/off
.FOOTERS              \" Page footers on/off
.HEADERS_AND_FOOTERS  \" Enable generation of both headers and footers
.HEADER_LEFT
.HEADER_CENTER
.HEADER_RIGHT
.HEADER_CENTER_PAD
.HEADER_FAMILY
.HEADER_SIZE
.HEADER_PLAIN
.HEADER_COLOR
.HEADER_MARGIN
.HEADER_GAP
.HEADER_RULE            \" On or off
.HEADER_RULE_WEIGHT     \" Weight of the rule
.HEADER_RULE_GAP        \" Distance of rule from header
.HEADER_RULE_COLOR      \" Colour of rule header


.SS Recto/verso page headers and footers
.RECTO_VERSO            \" Recto/verso headers and/or footers on/off
.SWITCH_HEADERS         \" Switch recto or verso header
.SWITCH_FOOTERS         \" Switch recto or verso footer
.HEADER_RECTO           \" String that constitutes a recto header
.HEADER_VERSO           \" String that constitutes a verso header
.FOOTER_RECTO           \" String that constitutes a recto footer
.FOOTER_VERSO           \" String that constitutes a recto footer


.SS Pagination
.PAGINATE               \" Pagination on/off
.PAGENUMBER             \" User-defined (starting) page number
.PAGENUM_STYLE          \" Digits, roman numerals, etc
.PAGENUM_ON_FIRST_PAGE  \" When footers are enabled
.DRAFT_WITH_PAGENUMBER  \" Attach draft/revision to page number


.SS Document and section cover (title) pages
.COVER                  \" Information to include in a section cover
.DOC_COVER              \" Information to include in a document cover
.COVERS                 \" Printing of section covers on/off
.DOC_COVERS             \" Printing of document covers on/off
.COVER_ADVANCE
.COVER_ATTRIBUTE_COLOR
.COVER_AUTHOR_COLOR
.COVER_AUTHOR_FAMILY
.COVER_AUTHOR_FONT
.COVER_AUTHOR_SIZE
.COVER_CHAPTER_TITLE_COLOR
.COVER_CHAPTER_TITLE_FAMILY
.COVER_CHAPTER_TITLE_FONT
.COVER_CHAPTER_TITLE_SIZE
.COVER_COPYRIGHT_COLOR
.COVER_COPYRIGHT_FAMILY
.COVER_COPYRIGHT_FONT
.COVER_COPYRIGHT_QUAD
.COVER_COPYRIGHT_SIZE
.COVER_COUNTS_PAGES
.COVER_DOCTYPE_COLOR
.COVER_DOCTYPE_FAMILY
.COVER_DOCTYPE_FONT
.COVER_DOCTYPE_SIZE
.COVER_FAMILY
.COVER_LEAD
.COVER_MISC_COLOR
.COVER_MISC_FAMILY
.COVER_MISC_FONT
.COVER_MISC_QUAD
.COVER_MISC_SIZE
.COVER_QUAD
.COVER_SUBTITLE_COLOR
.COVER_SUBTITLE_FAMILY
.COVER_SUBTITLE_FONT
.COVER_SUBTITLE_SIZE
.COVER_TITLE_COLOR
.COVER_TITLE_FAMILY
.COVER_TITLE_FONT
.COVER_TITLE_SIZE
.COVER_UNDERLINE
.DOC_COVER_ADVANCE
.DOC_COVER_ATTRIBUTE_COLOR
.DOC_COVER_AUTHOR_COLOR
.DOC_COVER_AUTHOR_FAMILY
.DOC_COVER_AUTHOR_FONT
.DOC_COVER_AUTHOR_SIZE
.DOC_COVER_AUTHOR_SIZE
.DOC_COVER_CHAPTER_TITLE_COLOR
.DOC_COVER_CHAPTER_TITLE_FAMILY
.DOC_COVER_CHAPTER_TITLE_FONT
.DOC_COVER_CHAPTER_TITLE_SIZE
.DOC_COVER_COPYRIGHT_COLOR
.DOC_COVER_COPYRIGHT_FAMILY
.DOC_COVER_COPYRIGHT_FONT
.DOC_COVER_COPYRIGHT_QUAD
.DOC_COVER_COPYRIGHT_SIZE
.DOC_COVER_COUNTS_PAGES
.DOC_COVER_DOCTYPE_COLOR
.DOC_COVER_DOCTYPE_FAMILY
.DOC_COVER_DOCTYPE_FONT
.DOC_COVER_DOCTYPE_SIZE
.DOC_COVER_FAMILY
.DOC_COVER_LEAD
.DOC_COVER_MISC_COLOR
.DOC_COVER_MISC_FAMILY
.DOC_COVER_MISC_FONT
.DOC_COVER_MISC_QUAD
.DOC_COVER_MISC_SIZE
.DOC_COVER_QUAD
.DOC_COVER_SUBTITLE_COLOR
.DOC_COVER_SUBTITLE_FAMILY
.DOC_COVER_SUBTITLE_FONT
.DOC_COVER_TITLE_COLOR
.DOC_COVER_TITLE_FAMILY
.DOC_COVER_TITLE_FONT
.DOC_COVER_TITLE_SIZE
.DOC_COVER_UNDERLINE


.SS Utilities
.ADD_SPACE            \" Add space to the top of a page
.BLANKPAGE            \" Output one or more blank pages
.DOC_LEAD_ADJUST      \" Adjust leading to fill pages
.COLLATE              \" Join documents (chapters/sections) together
.SHIM                 \" Move vertical position to next valid baseline
