.SH WEBPAGE AUTHORING

.JOBNAME      \" Split output into multiple files
.HX           \" Automatic heading level cut off
.BCL          \" Specify colours on a web page
.BGIMG        \" Specify background image
.URL          \" Create a URL using two parameters
.FTP          \" Create an FTP reference
.MTO          \" Create a HTML email address
.FTP          \" Create an FTP reference
.TAG          \" Generate an HTML name
.IMG          \" Include an image file
.PIMG         \" Include PNG image
.MPIMG        \" Place PNG on the margin and wrap text around it
.HnS          \" Begin heading
.HnE          \" End heading
.LK           \" Emit automatically collected links
.HR           \" Produce a horizontal rule
.NHR          \" Suppress automatic generation of rules
.HTL          \" Only generate HTML title
.HEAD         \" Add data to <head> block
.ULS          \" Unorder list begin
.ULE          \" Unorder list end
.OLS          \" Ordered list begin
.OLE          \" Ordered list end
.DLS          \" Definition list begin
.DLE          \" Definition list end
.LI           \" Insert a list item
.DC           \" Generate a drop capital
.HTML         \" Pass an HTML raw request to the device driver
.CDS          \" Code example begin
.CDE          \" Code example end
.ALN          \" Place links on left of main text
.LNS          \" Start a new 2-column table with links in the left
.LNE          \" End the 2-column table
.LINKSTYLE    \" Initialise default URL attributes
