.Sh RRRRRR Em IIIII IIII No RRRRRR Sy BBBBBB
.Sh RRRRRR Em IIIII Em IIII
.SH RRRRRR
RRRRRRRRRRRRRRRRRR
.Em IIIIII No RRRR Li CCCCCC \fB BBBBBB
BB \fR
.Ad RRRRRR Em IIII \fB BBBBBB \fR RRRRR
.Ed RRRRRR Em RRRR

.Bf -emphasis RRRRRRRRRR \" Comment
IIIIIIIIIIIII
.Sy BBBBBBBBB
IIIIIIIIIIIII

.Ef
RRRRRRRRRRRR


.Bf -symbolic
BBBBBBBBBBBBBBBBBB
.Li CCCCCCCCCCCCC\
CCCCCCCCCCCCCCCCCC
BBBBBBBB
.Ef RR
